version: 2
mergeable:
  - when: pull_request.*
    name: 'Single commit with mergeable@test email'
    validate:
      - do: commit
        message:
          regex: '^mergeable@test$'
          message_type: author_email
    pass:
      - do: merge
        merge_method: merge
