version: 2
mergeable:
  - when: pull_request.*
    name: 'Single commit with mergeable@test email'
    validate:
      - do: payload
        pull_request:
          commits: 1
      - do: commit
        message:
          regex: '^mergeable@test$'
          message_type: author_email
          single_commit_only: true
    pass:
      - do: merge
        merge_method: merge