version: 2
mergeable:
  - when: pull_request.*
    name: 'Commits with renovate[bot] email'
    validate:
      - do: commit
        message:
          regex: '"renovate[bot]" <29139614+renovate[bot]@users.noreply.github.com>'
          message_type: commiter_email
    pass:
      - do: merge
        merge_method: merge
