version: 2
mergeable:
  - when: pull_request.*
    name: 'Single commit with mergeable@test email'
    validate:
      - do: commit
        message:
          regex: '^Ch4s3r <patrick.lampe.dittmer@gmail.com>$'
          message_type: commiter_email
