version: 2
mergeable:
  - when: pull_request.opened, pull_request.synchronize, status.success, check_suite.completed
    name: 'Single commit with mergeable@test email'
    filter:
      - do: payload
        pull_request:
          commits:
            must_include:
              regex: '^1$'
    validate:
      - do: commit
        message_type: author_email
        must_include:
          regex: '^mergeable@test$'
    pass:
      - do: merge
        merge_method: merge