version: 2
mergeable:
  - when: pull_request.*
    name: 'Commits with renovate[bot] email'
    validate:
      - do: commit
        message:
          regex: '.*renovate.*'
          message_type: committer_email
    pass:
      - do: merge
        merge_method: merge
