version: 2
mergeable:
  - when: pull_request.*
    name: 'Single commit with 29139614+renovate[bot]@users.noreply.github.com email'
    validate:
      - do: commit
        message:
          regex: '^29139614\\+renovate\\[bot\\]@users\\.noreply\\.github\\.com$'
          message_type: committer_email
